apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  labels:
    {{- include "opendcs.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: database-migration
          image: "{{ .Values.image.repository }}/routingscheduler:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_TYPE
              value: "OPENTSDB"
            - name: DATABASE_URL
              value: "jdbc:postgresql://{{ include "database.hostname" .}}:5432/{{ .Values.postgresql.auth.database }}"
            - name: DATABASE_DRIVER
              value: "org.postgresql.Driver"
            - name: DATABASE_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
          command: ["echo",  "Migrated"]
      restartPolicy: Never
  backoffLimit: 4