{{ range $appName, $app := .Values.apps -}}
  {{ if $app.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$appName}}
  labels:
    {{- include "opendcs.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $appName }}
spec:  
  replicas: 1
  selector:
    matchLabels:
      {{- include "opendcs.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opendcs.labels" $ | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml $ | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: wait-for-migration
          image: ghcr.io/groundnuty/k8s-wait-for:v1.6
          imagePullPolicy: Always
          args:
            - "job"
            - "database-migration"
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opendcs.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $appName }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}/{{$appName}}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: test
              value: "{{$.Capabilities.KubeVersion}}"
            - name: KEYGENERATOR
              value: "decodes.sql.SequenceKeyGenerator"
            - name: DATABASE_TYPE
              value: "OPENTSDB"
            - name: DATABASE_URL
              value: "jdbc:postgresql://{{ include "database.hostname" $}}:5432/{{ include "database.name" $ }}"
            - name: DATABASE_DRIVER
              value: "org.postgresql.Driver"
            - name: DATABASE_USERNAME
              value: {{ $.Values.apps.user.username }}
            - name: DATABASE_PASSWORD
              value: {{ $.Values.apps.user.password }}
            {{ if $app.name -}}
            - name: APPLICATION_NAME
              value: "{{ $app.name }}"
            {{ end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          {{- with $.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
---
  {{ end }}
{{ end }}