{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opendcs.serviceAccountName" . }}
  labels:
    {{- include "opendcs.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watcher-role
rules:
- apiGroups: ["batch",""]
  resources: ["pods","services","deployments","jobs","secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lrgs-role
rules:
- apiGroups: ["lrgs.opendcs.org"]
  resources: ["ddsconnections", "drgsconnections"]
  verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watcher-role
subjects:
  - kind: ServiceAccount
    name: {{ include "opendcs.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lrgs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lrgs-role
subjects:
  - kind: ServiceAccount
    name: {{ include "opendcs.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}
