apiVersion: v1
kind: Service
metadata:
  name: {{ include "opendcs.fullname" . }}
  labels:
    {{- include "opendcs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dds
      protocol: TCP
      name: dds
  selector:
    {{- include "opendcs.selectorLabels" . | nindent 4 }}
