{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opendcs-operator.serviceAccountName" . }}
  labels:
    {{- include "opendcs-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lrgs-operator-role
rules:
- apiGroups: ["lrgs.opendcs.org"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch","apps",""]
  resources: ["pods","services","deployments","jobs","secrets","configmaps","statefulsets"]
  verbs: ["*"]
# If you want events
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lrgs-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lrgs-operator-role
subjects:
  - kind: ServiceAccount
    name: {{ include "opendcs-operator.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}
