apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ddsrecv.lrgs.opendcs.org
spec:
  group: lrgs.opendcs.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              oneOf:
                - required: ["username", "password"]
                - required: ["secret"]
              properties:
                hostname:
                  type: string
                port:
                  type: integer
                enabled: 
                  type: boolean
                username:
                  type: string
                password:
                  type: string
                secret:
                  type: string
                  description: "secret containing username and password keys (basic auth)"
  scope: Namespaced
  names:
    plural: ddsrecv
    singular: ddsrecv
    kind: DdsRecv