apiVersion: lrgs.opendcs.org/v1
kind: DdsConnection
metadata:
  name: local
spec:
  name: LocalTest
  hostname: local-lrgs.test
  username: testuser
---
apiVersion: lrgs.opendcs.org/v1
kind: DdsConnection
metadata:
  name: local2
spec:
  name: LocalTest2
  hostname: local2-lrgs.test
  username: testuser
---
apiVersion: v1
kind: Secret
type: lrgs.opendcs.org/ddsuser
metadata:
  name: testuser
stringData:
  username: testuser
  password: test
  roles: 
---